# This file was generated by GoReleaser. DO NOT EDIT.
cask "aat" do
  # The binaries are not notarized; strip the quarantine attribute so the
  # first run does not trip Gatekeeper.
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/aat"], must_succeed: false
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/aat-sandbox"], must_succeed: false
    end
  end

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "74df755056686f37e62181a5215cddc0be88dcea0f8a06fb31b04c925d95fbec"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "027d466e549b061f775373af8bec7f08e6b05a9c32a0147d8d2403441477207e"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3bdc7f1bb0ab19a43e1efa788df13e3b19e5f3c69dbe544696999f22b1cc42c"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bafd18244254036419ba943fef36f8cd9500afe80b3b965df776d152504de90"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_amd64.tar.gz"
    end
  end

  name "aat"
  desc "Model your API as a graph; run long-chain tests, layer matrices, and an MCP server from it"
  homepage "https://gburgyan.github.io/aat/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aat"
  binary "aat-sandbox"

  # No zap stanza required
end
