# This file was generated by GoReleaser. DO NOT EDIT.
cask "aat" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "855fd025be07be9d75934041232765e76b3d41d82e7ee58f8582f5ad05c2cf51"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "811d32072de09a09f9722bf79636315afc1116d42e9f31b953931b82ace3e95e"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "02335c705c81eb40c2709c6f624c431b9d2077e4762b0b974884bb288b890233"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32b53dc7cee43fda0a80cc8d6d8c9a68116805365be05fab040e34181c93bc82"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_amd64.tar.gz"
    end
  end

  name "aat"
  desc "Model your API as a graph; run long-chain tests, layer matrices, and an MCP server from it"
  homepage "https://gburgyan.github.io/aat/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aat"
  binary "aat-sandbox"

  postflight do
    if OS.mac?
      %w[aat aat-sandbox].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary}"]
      end
    end
  end

  # No zap stanza required
end
