# This file was generated by GoReleaser. DO NOT EDIT.
cask "aat" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7f81270da885eedf34c06e2105aea6bf62ed502f2e437d96caf4f1cdd3ab23b3"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e17f52f2c433c3e88d1126b3ea84a368497ac1c6e88fd2b5629f16dbfa47842f"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2045018cbd7f3391624d843e7f8ee1c410f651811b86df913588a59f4792b714"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "da6a55ffbc2dc9d8946c49b5beabc7b97f462aa0d4860edbf3206572300649e5"
      url "https://github.com/gburgyan/aat/releases/download/v#{version}/aat_linux_amd64.tar.gz"
    end
  end

  name "aat"
  desc "Model your API as a graph; run long-chain tests, layer matrices, and an MCP server from it"
  homepage "https://gburgyan.github.io/aat/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aat"
  binary "aat-sandbox"

  postflight do
    if OS.mac?
      %w[aat aat-sandbox].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary}"]
      end
    end
  end

  # No zap stanza required
end
